# Generated by Django 3.1.8 on 2021-04-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseset',
            old_name='workout_session_id',
            new_name='workout_session',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
